apiVersion: v1
kind: Secret
metadata:
  name: fleetbase-mysql
  namespace: fleetbase
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "#{fleetbaseMysqlRootPassword}#"
  MYSQL_PASSWORD: "#{fleetbaseMysqlPassword}#"
---
apiVersion: v1
kind: Secret
metadata:
  name: fleetbase-app
  namespace: fleetbase
type: Opaque
stringData:
  APP_KEY: "#{fleetbaseAppKey}#"
